# Generated by Django 4.1.4 on 2023-08-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=220)),
                ('question_text', models.CharField(max_length=500)),
                ('question_already_done', models.CharField(max_length=300)),
                ('question_tags', models.CharField(max_length=100)),
                ('question_pub_date', models.DateTimeField()),
            ],
        ),
    ]
